global:
  resolve_timeout: 5m
  smtp_from: 'Monitoring <monitoring@my-domain.tdl>'
  smtp_smarthost: mail.my-domain.tdl
  smtp_require_tls: true
  smtp_auth_username: 'my-mail-user'
  smtp_auth_password: 'my-mail-password'
  
route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'default-email'
  
  routes:
  - match:
      alertname: Docker_Service_Not_Active
    receiver: service-email
    routes:
    - match:
        name: docker.socket
      receiver: critial-email
      continue: true
  - match:
      severity: critical
    receiver: default-email
 
receivers:
- name: 'default-email'
  email_configs:
  - to: "alert-group-a@my-domain.tdl"
    send_resolved: true
- name: 'service-email'
  email_configs:
  - to: "alert-group-b@my-domain.tdl"
    send_resolved: true
- name: 'critial-email'
  email_configs:
  - to: "alert-group-c@my-domain.tdl"
    send_resolved: true
