apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workspace-pvc
  labels:
    {{- include "storage.labels" . | nindent 4 }}
spec:
  storageClassName: local-path
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Mi