replicaCount: 1

image:
  repository: prom/prometheus
  pullPolicy: IfNotPresent
  tag: ""

service:
  type: ClusterIP
  port: 9090

ingress:
  entryPoint: web

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
