apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "demo-app.fullname" . }}-ir
  labels:
    {{- include "demo-app.labels" . | nindent 4 }}
spec:
  entryPoints:
  - {{ .Values.ingress.entryPoint }}
  routes:
  - match: "Host(`{{ .Values.global.baseUrl }}`)" 
    kind: Rule
    services:
    - name: {{ include "demo-app.fullname" . }}
      port: {{ .Values.service.port }}
