apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: demo-apps-role-binding
  labels:
    {{- include "demo-app.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: demo-apps-role
subjects:
  - kind: ServiceAccount
    name:  demo-apps-service-account
