apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: demo-apps-role
  labels:
    {{- include "demo-app.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - pods
  - pods/log
  verbs:
  - get
  - list
  - delete
  - create  
  - update
