replicaCount: 1

image:
  repository: prom/alertmanager
  pullPolicy: IfNotPresent
  tag: ""

service:
  type: ClusterIP
  port: 9093

ingress:
  entryPoint: web

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
