apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "blackbox-exporter.fullname" . }}
  labels:
    {{- include "blackbox-exporter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "blackbox-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "blackbox-exporter.selectorLabels" . | nindent 8 }}
        app: blackbox-exporter
    spec:
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 9115
              protocol: TCP
          volumeMounts:
            - name: shared
              mountPath: /etc/blackbox_exporter
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      initContainers:
        - name: init-cfg
          image: busybox:1.28
          command: ["sh", "-c", "cp /workspace/blackbox-exporter/blackbox.yml /shared/config.yml"]
          volumeMounts:
            - name: shared
              mountPath: /shared
            - name: workspace
              mountPath: /workspace
      volumes:
        - name: workspace
          persistentVolumeClaim:
            claimName: workspace-pvc
        - name: shared
          emptyDir:               

  