apiVersion: v1
kind: Service
metadata:
   name: ssh-jumpbox-svc
   namespace: windows
spec:
  type: ClusterIP
  selector:
      app: ssh-jumpbox
  ports:
    - name: ssh
      port: 22
      targetPort: 22
      protocol: TCP
    - name: prometheus
      port: 9182
      targetPort: 9182
      protocol: TCP
  