apiVersion: v1
kind: Service
metadata:
   name: tracing-ui-srv
spec:
   ports:
      - port: 80
        targetPort: 5001
        name: app
   selector:
      stack: tracing
      app: ui

---
apiVersion: v1
kind: Service
metadata:
   name: tracing-stock-srv
spec:
   ports:
      - port: 80
        targetPort: 6001
        name: app
   selector:
      stack: tracing
      app: stock
---
apiVersion: v1
kind: Service
metadata:
   name: tracing-payment-srv
spec:
   ports:
      - port: 80
        targetPort: 7001
        name: app
   selector:
      stack: tracing
      app: payment
---
