apiVersion: v1
kind: Service
metadata:
  name: {{ include "jumpbox.fullname" . }}
  labels:
    {{- include "jumpbox.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.http }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.ssh }}
      targetPort: ssh
      protocol: TCP
      name: ssh
  selector:
    {{- include "jumpbox.selectorLabels" . | nindent 4 }}
