apiVersion: v1
kind: Service
metadata:
   name: ssh-jumpbox-child-svc
spec:
  type: ClusterIP
  selector:
      app: ssh-jumpbox-child
  ports:
    - name: ssh
      port: 22
      targetPort: 22
      protocol: TCP
    - name: prometheus
      port: 5001
      targetPort: 5001
      protocol: TCP
  