apiVersion: v1
kind: Service
metadata:
  name: ssh-jumpbox-main-lb
  namespace: jumpbox
spec:
  type: LoadBalancer
  ports:
    - port: 8022
      targetPort: 22
      protocol: TCP
      name: ssh
  selector:
    app: ssh-jumpbox-main