apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "smtp4dev.fullname" . }}-ir
spec:
  entryPoints:
  - {{ .Values.ingress.entryPoint }}
  routes:
  - match: "Host(`smtp4dev.{{ .Values.global.baseUrl }}`)" 
    kind: Rule
    services:
    - name: {{ include "smtp4dev.fullname" . }}
      port: {{ .Values.service.port }}
