name: "metrics"

on:
  push:
    branches: [ main ]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: |
        dotnet restore dotnet/opentelemetry/external/ExternalService.csproj
    - name: Build
      run: |
        dotnet build --no-restore dotnet/opentelemetry/external/ExternalService.csproj
    - name: Publish
      run: |
        dotnet publish -c release -r linux-x64 --no-self-contained -o dotnet/opentelemetry/external/out/ dotnet/opentelemetry/external/ExternalService.csproj

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
         images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
         tags: |
           type=raw,value=external

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./dotnet/opentelemetry/external/
        platforms: linux/amd64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
     


